# Wybrane metody matematyczne w analizie danych - pracownia 1

### Marcin Koźniewski
#### 18 listopada 2023

Kilka przydatnych zasobów:
* https://numpy.org/doc/stable/reference/routines.linalg.html
* https://numpy.org/doc/stable/reference/routines.array-creation.html


### Ćwiczenia

Ćwiczenie 1. Zdefiniuj macierze

$A=\begin{bmatrix}
1 & 2 & 3 \\
2 & 2 & 2  
\end{bmatrix}$

$B=\begin{bmatrix}
1 & 0 & 1 \\
-1 & 5 & 2  
\end{bmatrix}$

$C=\begin{bmatrix}
1 & 2 \\
-1 & 1  
\end{bmatrix}$

In [4]:
import numpy as np
A=np.array( [[1, 2, 3], [2, 2, 2]] )
B=np.array( [[1,0,1], [-1,5,2]] )
C=np.array( [[1,2], [-1,1]] )
A

array([[1, 2, 3],
       [2, 2, 2]])

Ćwiczenie 2. Spróbuj wykonać poniższe działania na macierzach zdefiniowancych w Ćwiczeniu 1. Czy jest to możliwe. Skomentuj wyniki:
1. $A+B$
1. $\frac{1}{2}A$
1. $A^T$
1. $CC$ (mnożenie)
1. $CA$ (mnożenie)
1. $AC$ (mnożenie)
1. $A+C$
1. $C^{-1}$

In [2]:
A+B

array([[2, 2, 4],
       [1, 7, 4]])

In [3]:
0.5*A

array([[0.5, 1. , 1.5],
       [1. , 1. , 1. ]])

In [4]:
A.T

array([[1, 2],
       [2, 2],
       [3, 2]])

In [2]:
C @ C

array([[-1,  4],
       [-2, -1]])

In [6]:
C @ A

array([[ 5,  6,  7],
       [ 1,  0, -1]])

In [7]:
A @ C #niewłaście wymiary macierzy C - 2 wiersze A - 3 kolumny 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

niewłaście wymiary macierzy C - 2 wiersze A - 3 kolumny 

In [8]:
A+C #różne wymiary macierzy

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [3]:
print(np.linalg.det(C)) #różne od 0!
np.linalg.inv(C)

3.0000000000000004


array([[ 0.33333333, -0.66666667],
       [ 0.33333333,  0.33333333]])

Ćwiczenie 2. Zdefiniuj poniższe wektory i wykonaj działania.
1. $u=[3,2,2]$
1. $w=[2,0,1]$
1. $v=[3,1] $


1. $w^T$
1. $Aw^T$
1. $u+w$

In [11]:
u=np.array([[3,2,2]])
w=np.array([[2,0,1]])
v=np.array([[3,1]])

In [12]:
w.T

array([[2],
       [0],
       [1]])

In [13]:
A @ w.T

array([[5],
       [6]])

A ma 2 wiersze i 3 kolumny (stąd wektor długości 2).

In [13]:
u+w

array([[5, 2, 3]])

Ćwiczenie 3. Policz średnią ważoną w każdym z wierszy dwolnej macierzy o 3 kolumnach z wagami dla kolejnych kolumn 2, 5 i 1.

$$Średnia\;ważona = \frac{a_1w_1+a_2w_2+a_3w_3}{w_1+w_2+w_3}$$

In [14]:
M = np.array( ((1, 2, 3), (1, 2, 2), (0, 0, 1)) ) #można też używać nawiasów okrągłych
wagi = np.array(((2,5,1)))
print(M)
print(sum(wagi))
M @ wagi.T / sum(wagi)

[[1 2 3]
 [1 2 2]
 [0 0 1]]
8


array([1.875, 1.75 , 0.125])

### Zadania samodzielne / praca domowa
Proszę sporządzić raport z wykonania poniższych zadań. Może to być prosty plik tekstowy lub notes Jupyter z wykonanymi poleceniami i wynikiem ich wywołania z dodatkiem komentarzy, jeśli są one potrzebne (wystąpił błąd).

Zadanie 1. Zdefiniuj Podane macierze i wektory


1. $A=\begin{bmatrix}
1 & 0 & 1 & 2\\
0 & 1 & -2 & 0
\end{bmatrix}$
1. $B=\begin{bmatrix}
1 & 2 & 1 & 0\\
1 & 0 & -1 & 1 \\
2 & 1 & 0 & 0
\end{bmatrix}$
1. $C=\begin{bmatrix}
1 & 2 & 1 & 0\\
1 & 0 & -1 & 1 \\
2 & 1 & 0 & 0\\
2 & 2 & 0 & 1
\end{bmatrix}$
1. $D=\begin{bmatrix}
1 & 0 & 2 \\
0 & 2 & 1
\end{bmatrix}$
1. $E=\begin{bmatrix}
1 & 0 & -1 \\
-1 & 2 & 2
\end{bmatrix}$
1. $F=\begin{bmatrix}
0 & 3 \\
2 & 1
\end{bmatrix}$
1. $G=\begin{bmatrix}
2 & 0 & 3 \\
-1 & 1 & 2\\
0 & 1 & -1
\end{bmatrix}$
1. identycznościowa $H=\begin{bmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}$
1. identycznościowa $I=\begin{bmatrix}
1 & 0\\
0 & 1
\end{bmatrix}$


1. $\mathbf{w}=[1,2,1,0]$
1. $\mathbf{u}=[1,0,-1,1]$   
1. $\mathbf{v}=[2,1,0,0]$
1. $\mathbf{x}=[4,4,4]$
1. $\mathbf{z}=[1,2,1,2]$



In [28]:
a = np.array([[1,0,1,2],[0,1,-2,0]])
b = np.array([[1,2,1,0],[1,0,-1,0],[2,1,0,0]])
c = np.array([[1,2,1,0],[1,0,-1,1],[2,1,0,0],[2,2,0,1]])
d = np.array([[1,0,2],[0,2,1]])
e = np.array([[1,0,-1],[-1,2,2]])
f = np.array([[0,3],[2,1]])
g = np.array([[2,0,3],[-1,1,2],[0,1,-1]])
h = np.identity(4)
i = np.identity(2)
w = np.array([[1,2,1,0]])
u = np.array([[1,0,-1,0]])
v = np.array([[2,1,0,0]])
x = np.array([[4,4,4]])
z = np.array([[1,2,1,2]])

Zadanie 2. Spróbuj dokonać obliczeń na zdefiniowanych obiektach z Zadania 1. Ewentualne błędy wykonania skomentuj.
1. $D+E$
1. $DE^T$
1. $D^TE$
1. $FF$
1. $GGGG$
1. $(DE^T)+F$
1. $-G$
1. $(D^TE)+G$
1. $FI$
1. $IFII$
1. $G^{-1}$
1. $H^{-1}$
1. $C^{-1}$
1. $F^{-1}$


1. $w+v$
1. $xG$
1. $Gx$
1. $Gx^T$
1. $ww^T$
1. $w^Tw$
1. $zz^T$
1. $z^Tz$
1. $Iv^T$
1. $Du^T$
1. $BCB^TGx^T$
1. $BCz^T$

In [42]:
calc1 = d+e
calc2 = d @ e.T
calc3 = d.T @ e
calc4 = f @ f
calc5 = g @ g @ g @ g
calc6 = d @ e.T + f
calc7 = -g
calc8 = d.T @ e + g
calc9 = f @ i
calc10 = i @ f @ i @ i
calc11 = np.linalg.inv(g)
calc12 = np.linalg.inv(h)
calc13 = np.linalg.inv(c)
calc14 = np.linalg.inv(f)

calc1_ = w+v
calc2_ = x @ g
#calc3_ = g @ x brak zgodnosci wymiarow
calc4_ = g @ x.T
calc5_ = w @ w.T
calc6_ = w.T @ w
calc7_ = z @ z.T
calc8_ = z.T @ z
#calc9_ = i @ v.T brak zgodnosci wymiarow
#calc10_ = d @ u.T brak zgodnosci wymiarow
calc11_ = b @ c @ b.T @ g @ x.T
calc12_ = b @ c @ z.T

Zadanie 3. Policz wyznaczniki i odwrotności macierzy $F$, $G$, $H$ i $I$


In [45]:
detf = np.linalg.det(f)
detg = np.linalg.det(g)
deth = np.linalg.det(h)
deti = np.linalg.det(i)

invi = np.linalg.inv(f)
invg = np.linalg.inv(g)
invh = np.linalg.inv(h)
invi = np.linalg.inv(i)

Zadanie 4. Dla macierzy $F$, $C$ i $I$ policz wektory i wartości własne (`np.linalg.eig`) .

In [ ]:
eigf = np.linalg.eig(f)
eigc = np.linalg.eig(c)
eigi = np.linalg.eig(i)

Zadanie 5. Policz średnie dla każdego wiersza w dowolnej macierzy o 5 kolumnach. (podpowiedź: wszystkie wagi równe)

In [49]:
matrix = np.random.random((3,5))
multiply = np.ones(5)
matrix @ multiply.T / 5

array([0.69986115, 0.59977759, 0.46047669])